//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSPR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not
    {
        public int NotID { get; set; }
        public int OgrenciDersID { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Odev { get; set; }
    
        public virtual OgrenciDers OgrenciDers { get; set; }
    }
}
